services:
  ui-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18000:80"
    restart: unless-stopped
    container_name: ui-app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3